name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Show Current working directory and List files
        run: |
          pwd
          ls -la
          echo "GITHUB_SHA = $GITHUB_SHA"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
        shell: bash
      - name: Checkout
        uses: actions/checkout@v1
      - name: Show Current working directory and List files after checkout
        run: |
          pwd
          ls -la
        shell: bash
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Vinay
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      